#!/bin/bash

echo "🔧 Script para agregar archivos nativos al proyecto Xcode"
echo ""
echo "📋 INSTRUCCIONES MANUALES:"
echo ""
echo "1. Xcode debe estar abierto con el workspace: qobuzmobilev2.xcworkspace"
echo ""
echo "2. En Xcode, busca la carpeta amarilla 'qobuzmobilev2' en el navegador izquierdo"
echo ""
echo "3. Haz CLIC DERECHO sobre 'qobuzmobilev2' → 'Add Files to qobuzmobilev2...'"
echo ""
echo "4. En el diálogo que aparece:"
echo "   - Navega a: $(pwd)/ios/"
echo "   - Selecciona AMBOS archivos:"
echo "     ✅ RNEqualizer.swift"
echo "     ✅ RNEqualizer.m"
echo ""
echo "5. Asegúrate de marcar:"
echo "   ✅ 'Copy items if needed'"
echo "   ✅ 'Add to targets: qobuzmobilev2'"
echo "   ✅ 'Create groups'"
echo ""
echo "6. Click 'Add'"
echo ""
echo "7. Verifica Build Settings:"
echo "   - Selecciona el proyecto (ícono azul)"
echo "   - Ve a 'Build Settings'"
echo "   - Busca 'Objective-C Bridging Header'"
echo "   - Debe decir: qobuzmobilev2/qobuzmobilev2-Bridging-Header.h"
echo ""
echo "8. Una vez agregados, ejecuta:"
echo "   cd $(pwd)"
echo "   npx expo run:ios"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 Archivos listos para agregar:"
ls -lh "$(pwd)/ios/RNEqualizer.swift" "$(pwd)/ios/RNEqualizer.m"
echo ""
echo "✅ Bridging Header configurado:"
cat "$(pwd)/ios/qobuzmobilev2/qobuzmobilev2-Bridging-Header.h"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
